### ISSUE TITLE
Async functions?

### ISSUE THREAD

**Issue by px0** [uswitch/lambada#4]
Hey, how would I work with asynchronous functions? I there a way to succeed through the context or something like that?
Thanks!

**Comment by ragnard** [comment]
As far as I'm aware there's no asynchronous Java interface for AWS Lambda, and I'm not even sure such an interface would make a lot of sense. The java [`Context`](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/Context.java) provides no such functionality. 

If you need to use Java methods that complete asynchronously then you can always use a promise/future or similar in your Lambda function and block on that until the asynchronous operation completes. Does that make sense?

**Comment by px0** [comment]
That makes perfect sense, thank you! I came to this from the cljs-lambda plugin and it, being node based, does everything asynchronously. My brain didn't make the switch :)
Thanks a lot for the quick answer!
